### ISSUE TITLE
Is it a ProGuard-related issue?

### ISSUE THREAD

**Issue by sevar83** [salomonbrys-deprecated/Native-Crash-Handler#3]
Hi, I've run into a problem. The debug version starts fine but the signed release version (optimized and obfuscated with ProGuard) crashes. I have the line:

-keepclasseswithmembernames class \* {
    native <methods>;
}

and also all the suggested ACRA-specifics.

Here's the decoded tombstone... Does anyone have some idea?

$ adb shell cat /data/tombstones/tombstone_06 | ndk-stack -sym workspace/android-spatialite/obj/local/armeabi-v7a

*********\* Crash dump: **********
Build fingerprint: 'samsung/espressowifixx/espressowifi:4.0.3/IML74K/P3110XWALD2:user/release-keys'
pid: 21400, tid: 21415, name: AsyncTask #1  >>> com.buildware.geoworld <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000002c
Stack frame #00  pc 0004c838  /system/lib/libdvm.so
Stack frame #01  pc 00020a2d  /data/app-lib/com.buildware.geoworld-1/libandroid_spatialite.so (nativeCrashHandler_onLoad+76): Routine GetMethodID in /home/sevar/workspace/android-spatialite/ndk-modules/libnativehelper/libnativehelper/include/nativehelper/jni.h:505
Stack frame #02  pc 0001d3ab  /data/app-lib/com.buildware.geoworld-1/libandroid_spatialite.so (JNI_OnLoad+102): Routine JNI_OnLoad in /home/sevar/workspace/android-spatialite/jni/org_spatialite_database_SQLiteDatabase.cpp:628
Stack frame #03  pc 0004f61b  /system/lib/libdvm.so (dvmLoadNativeCode(char const_, Object_, char**)+470)
Stack frame #04  pc 00066381  /system/lib/libdvm.so
Stack frame #05  pc 00027660  /system/lib/libdvm.so

**Comment by SalomonBrys** [comment]
The project has been discontinued.
