### ISSUE TITLE
Native method not found

### ISSUE THREAD

**Issue by 4ntoine** [salomonbrys-deprecated/Native-Crash-Handler#4]
I've added pom.xml, compiled module as maven apklib and added as maven dependency.
I've also compiled my native lib with NativeCrashHandler.cpp and .h.

On app run (Application.onCreate()) i'm getting exception:

```
03-04 17:02:36.327: ERROR/AndroidRuntime(2783): FATAL EXCEPTION: main
        java.lang.UnsatisfiedLinkError: Native method not found: com.github.nativehandler.NativeCrashHandler.nRegisterForNativeCrash:()Z
        at com.github.nativehandler.NativeCrashHandler.nRegisterForNativeCrash(Native Method)
        at com.github.nativehandler.NativeCrashHandler.registerForNativeCrash(NativeCrashHandler.java:23)
```

so it looks like some .so lib is missing

**Comment by 4ntoine** [comment]
i've found Java_com_github_nativehandler_NativeCrashHandler_nUnregisterForNativeCrash in NativeCrashHandler.cpp but it seems that System.loadLibrary() should be invoked before new NativeCrashHandler().registerForNativeCrash(this); is there is no word about it in Usage

**Comment by 4ntoine** [comment]
Is there any opportunity to make loading NativeCrashHandler separated from loading native library? Case: native code (.so) is downloaded from the internet and it's not attached to any activity. The best solution would be to load libraries separately (and NativeCrashHandler on App.onCreate())

**Comment by SalomonBrys** [comment]
The project has been discontinued.
