### ISSUE TITLE
Not able to get the NativeCrashHandler.jar 

### ISSUE THREAD

**Issue by ItsRajesh4uguys** [salomonbrys-deprecated/Native-Crash-Handler#5]
Hi,

I am not able to get the  NativeCrashHandler.jar  from  NativeCrashHandler.tgz file in Mac. 
Please look at the attached image and get back to me if possible. 

![screen shot 2014-07-24 at 12 39 28 pm](https://cloud.githubusercontent.com/assets/2851981/3684823/8dbbd438-1301-11e4-85b0-b966d90c7b69.png)

**Comment by SalomonBrys** [comment]
Hi,
this project is discontinued and no longer maintained.

I strongly advise against using it since **it does **_not**_ work**.

**Comment by ItsRajesh4uguys** [comment]
Thanks for your message.
